SELECT USER FROM DUAL;

CREATE USER yoonwonju IDENTIFIED BY rootroot;

GRANT CONNECT, RESOURCE, CREATE SYNONYM, CREATE VIEW 
   TO yoonwonju;

SELECT *
  FROM DBA_USERS 
 WHERE username = 'YOONWONJU';